name: Packer Builder - vSphere

on:
  workflow_call:
    inputs:
        machine-prefix:
          type:                   string
          required:               true
          description:            'The machine name prefix used for the image'

        template-dir:
          type:                   string
          required:               true
          description:            'The path to the dir containing the packer template HCL files - i.e. `infra/templates/windows-server-2019`'

        install-type:
          type:                   string
          required:               true
          description:            'The type of image install - this influences what variable and autounattend files to use.  This should be a subdir of the main template dir'

        environment:
          type:                   string
          required:               true
          description:            'The environment where to build the template in - could be lab_infra, prod_infra, lab_vdi etc.'

jobs:
  vars_build:
    runs-on:                      [ self-hosted,linux,packer]
    outputs:
      githubsha:                  ${{ steps.extract-sha.outputs.shortsha }}
      vm_build_name:              ${{ steps.vm_build_name.outputs.vm_build_name }}
    strategy:
      fail-fast: true
    steps:
      - name:                     Get current date
        run:                      echo "date=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_OUTPUT"
        id:                       date

      - name:                     Extract SHA and store in output var
        run:                      echo "shortsha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
        id:                       extract-sha

      - name:                     Build machine name
        run:                      echo "vm_build_name=$(echo ${{ inputs.machine-prefix }}-${{ steps.date.outputs.date }}-${{ steps.extract-sha.outputs.shortsha }})" >> "$GITHUB_OUTPUT"
        id:                       vm_build_name

  packer_build:
    needs:                        [ vars_build ]
    runs-on:                      [ self-hosted,linux,packer ]
    strategy:
      fail-fast: true
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PACKER_PRIV_KEY }}
          name: id_ed25519_packer
          known_hosts: |
            github.com,13.237.44.5 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp
            5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xh
            HTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4y
            CE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          # known host not in use just putting here to prevent from failing/ complaining
          if_key_exists: replace #/ ignore / fail; optional (defaults to fail)
      - name:                     Checkout repo to workspace
        uses:                     actions/checkout@v2

      - name:                     Setup `packer`
        uses:                     hashicorp/setup-packer@v2.0.0
        id:                       packer-setup
        with:
          version:                latest

      - name:                     🚧 Initialise Packer Template
        id:                       packer-init
        run:                      "packer init ${{ inputs.template-dir }}"

      - name:                     🧐 Validate Packer Template
        id:                       packer-validate
        run:                      "packer validate --syntax-only ${{ inputs.template-dir }}"

      - name:                     👷‍♀️ Initiate-Build
        id:                       packer-build
        run: >
          packer build
          -var=vSphere_password="${{ secrets.VSPHERE_PASSWORD }}"
          -var=passwdstateapikey="${{ secrets.PASSWDSTATEAPIKEY }}"
          -var=vm_build_name=${{ needs.vars_build.outputs.vm_build_name }}
          -var-file=${{ inputs.template-dir }}/install-types/${{ inputs.install-type }}/vars.pkrvars.hcl
          -var-file=build-environments/${{ inputs.environment }}.pkrvars.hcl
          ${{ inputs.template-dir }}
